M48
; DRILL file {KiCad (6.0.2-0)} date Thursday, 06 October 2022 at 01:55:03 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-06T13:55:03+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X139.15Y-88.11
T1
X132.1Y-88.11G85X131.8Y-88.11
G05
T0
M30
