M48
; DRILL file {KiCad (6.0.2)} date Sun Jul 10 22:33:02 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-10T22:33:02+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X160.72Y-105.575
X160.72Y-110.425
T2
X163.75Y-105.275
X163.75Y-110.725
T0
M30
